version: '3'
services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config:/consul/config
    command: ["sh", "/consul/config/start.sh"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 5s
      timeout: 2s
      retries: 5

  product-calculator:
    image: product-calculator:latest
    container_name: product-calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - default
    command: sh -c "sleep 10 && exec $0 $@"

networks:
  default:
    driver: bridge
