###
POST http://localhost:8080/calculator
Content-Type: application/json

{
  "productId" : "BC986388-A860-42E5-BFBB-266332210E77",
  "amount": 10
}

###
POST http://localhost:8080/calculator/discount/amount
Content-Type: application/json

{
  "productId" : "BC986388-A860-42E5-BFBB-266332210E77",
  "amount": 10
}

###
POST http://localhost:8080/calculator/discount/percentage
Content-Type: application/json

{
  "productId" : "BC986388-A860-42E5-BFBB-266332210E77",
  "amount": 10
}

